### PR TITLE
fix(gltf): replace deprecated md5 assets

### PR DESCRIPTION
**Pull request by jdrueckert**
# How to test

1. Start a `GooKeeper` gameplay
2. Take care that the gooeys don't kill you :sweat_smile: 
3. Use `spawnPrefab <prefab>` command in the in-game terminal (open via `F1`) to spawn the following prefabs
   * blueGooey
   * yellowGooey
   * redGooey
   * gooeyHatchling
   * visitor (will likely crash the game without changes from https://github.com/Terasology/GooKeeper/pull/26 being present)
4. Check that the models are visible and the height offset seems about right (fully above the ground but not obviously floating in the air)

### CODE REVIEW

**Comment by jdrueckert** [comment]
[GTLF support](https://trello.com/c/lZ8TVDwN/10-gtlf-support)

**Review by skaldarnar — DISMISSED** [review]
Models are showing up, but there are a few things that are still off:

- models are moving backwards
- the hatchling is way bigger than the other gooeys - that seems wrong
- they all move synchronized (that's likely due to how pathfinding updates entities)

**Comment by jdrueckert** [comment]
Models not moving forward is mentioned in https://github.com/MovingBlocks/Terasology/issues/4156
I'll take another look at the hatchling, probably forgot to fix the scaling.
Synchronized moving might be something @casals could be interested in?

**Comment by casals** [comment]
IIRC that's pathfinding alright (assuming I understood it correctly). Deer movement (WA + Behaviors) takes that into consideration by (i) randomizing directions (for the next movement) and (ii) probabilistic roll on each deer actually moving for each cycle. I suggest using the `stray` behavior as a possible solution for sync movement - if (i) + (ii) is an acceptable solution for this case, that's what I'd recommend (at least until we can circle back to Pathfinding).

**Review by skaldarnar — APPROVED** [review]
Approving as all models are visible again.

@jdrueckert the worldly tooltip for the gooey hatchling still does not show anything for me (display names are working fine for the other gooeys).

@casals to clarify, the gooey movement seems to be randomized (they are not walking all in the same direction or such), but they all turn at the same point in time. Nothing critical, just something I noticed...

**Comment by jdrueckert** [comment]
@skaldarnar Right forgot about that tooltip... guess there's a tooltip component missing in the prefab. I'll see about a follow-up PR
Concerning the movement, I opened https://github.com/Terasology/GooKeeper/issues/28

**Pull request merged**
